backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: content/uploads
public_folder: ../../../content/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "datetime", widget: "datetime", format: "ddd Do MMMM, YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
    - file: "src/pages/recommendations/index.md"
      label: "Recommendations"
      name: "recommendations"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "recommendation"}
        - label: Reviews
          name: reviews
          widget: list
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "Review", name: "body", widget: "markdown"}