backend:
  name: git-gateway
  branch: gatsby

publish_mode: editorial_workflow

media_folder: content/uploads
public_folder: ../../../content/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}